### ISSUE TITLE
Обрезаны названия кнопок

### ISSUE THREAD

**Issue by Wazzap007** [LynxarA-Coding/CodeTrade#1]
![image](https://user-images.githubusercontent.com/45575319/199195589-1f7d4257-b2c4-4a82-a4f3-5c4447656cc8.png)

**Comment by Wazzap007** [comment]
Еще внизу справа не влезла надпись тоже.

**Comment by lynxaradev** [comment]
Данный баг исправлен в обновлении Release 1.0.3
Скачать: [release 1-0-3](https://github.com/LynxarA-Coding/CodeTrade/releases/tag/release-1.0.3)
