### ISSUE TITLE
pickupand dropoff location text not showing untill typed in

### ISSUE THREAD

**Issue by AndrewEdgers** [LynxarA-Coding/CodeTrade#2]
on program load 
![image](https://user-images.githubusercontent.com/38178665/203566096-bc793ecf-f760-48cb-8682-4c1cf17fd546.png)

after typing and erasing text
![image](https://user-images.githubusercontent.com/38178665/203566599-0487f370-632b-4d98-b59e-063eb675c45d.png)

also incorrect language placeholder

**Comment by lynxaradev** [comment]
Thank you for reporting an issue. I will delete this Placeholder in the new version in the patch.
This text wasn't supposed to be there.

I will close this issue as soon as I fix this and replace the .exe file

**Comment by lynxaradev** [comment]
Problem was fixed in [pushed commit](https://github.com/LynxarA-Coding/CodeTrade/commit/d175199e7131d68a346394311623abfeb4968315)

You can download an exe from the last release to get an updated version
